CREATE TABLE recipe
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    instructions TEXT
);

CREATE TABLE recipe_ingredient
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    quantity DOUBLE NOT NULL,
    unit      VARCHAR(50),
    recipe_id BIGINT,
    FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE
);