CREATE TABLE inventory
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE ingredient
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    quantity DOUBLE NOT NULL,
    unit         VARCHAR(50),
    inventory_id BIGINT,
    FOREIGN KEY (inventory_id) REFERENCES inventory (id) ON DELETE CASCADE
);